config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :progresses
  resources :goals
  root to: 'goals#index'
end

app/controllers/progresses_controller.rb
class ProgressesController < ApplicationController
  before_action :set_progress, only: [:show, :edit, :update, :destroy]

  # GET /progresses
  # GET /progresses.json
  def index
    @progresses = Progress.all
  end

  # GET /progresses/1
  # GET /progresses/1.json
  def show
  end

  # GET /progresses/new
  def new
    @progress = Progress.new
  end

  # GET /progresses/1/edit
  def edit
  end

  # POST /progresses
  # POST /progresses.json
  def create
    @progress = Progress.new(progress_params)

    respond_to do |format|
      if @progress.save
        format.html { redirect_to @progress, notice: 'Progress was successfully created.' }
        format.json { render :show, status: :created, location: @progress }
      else
        format.html { render :new }
        format.json { render json: @progress.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /progresses/1
  # PATCH/PUT /progresses/1.json
  def update
    respond_to do |format|
      if @progress.update(progress_params)
        format.html { redirect_to @progress, notice: 'Progress was successfully updated.' }
        format.json { render :show, status: :ok, location: @progress }
      else
        format.html { render :edit }
        format.json { render json: @progress.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /progresses/1
  # DELETE /progresses/1.json
  def destroy
    @progress.destroy
    respond_to do |format|
      format.html { redirect_to progresses_url, notice: 'Progress was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_progress
      @progress = Progress.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def progress_params
      params.require(:progress).permit(:goal_id, :points, :entry_date)
    end
end

app/helpers/progresses_helper.rb
module ProgressesHelper
end

app/views/progresses/_form.html.slim
= form_for @progress do |f|
  - if @progress.errors.any?
    #error_explanation
      h2 = "#{pluralize(@progress.errors.count, "error")} prohibited this progress from being saved:"
      ul
        - @progress.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :goal, class: 'label'
    
    .control= f.collection_select :goal_id, Goal.order(:name), :id, :name, {}, { class: 'input' }
  .field
    = f.label :points, class: 'label'
    .control= f.number_field :points, placeholder: f.object.class.human_attribute_name(:points), class: 'input', step: :any
  .field
    = f.label :entry_date, class: 'label'
    .control= f.date_field :entry_date, placeholder: f.object.class.human_attribute_name(:entry_date), class: 'input'
  .actions = f.submit

app/views/progresses/edit.html.slim
h1 Editing progress

== render 'form'

=> link_to 'Show', @progress
'|
=< link_to 'Back', progresses_path

app/views/progresses/index.html.slim
h1 Listing progresses

table.table
  thead
    tr
      th Goal
      th Points
      th Entry date
      th
      th
      th

  tbody
    - @progresses.each do |progress|
      tr
        td = progress.goal
        td = progress.points
        td = progress.entry_date
        td = link_to 'Show', progress
        td = link_to 'Edit', edit_progress_path(progress)
        td = link_to 'Destroy', progress, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Progress', new_progress_path

app/views/progresses/new.html.slim
h1 New progress

== render 'form'

= link_to 'Back', progresses_path

app/views/progresses/show.html.slim
p#notice = notice

p
  strong Goal:
  = @progress.goal
p
  strong Points:
  = @progress.points
p
  strong Entry date:
  = @progress.entry_date

=> link_to 'Edit', edit_progress_path(@progress)
'|
=< link_to 'Back', progresses_path