config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :progresses
  resources :goals
  root to: 'goals#index'
end

app/models/goal.rb
# frozen_string_literal: true

class Goal < ApplicationRecord
  has_many :progresses

  validates :benchmark, numericality: true
end

app/controllers/goals_controller.rb
# frozen_string_literal: true

# GoalsController
class GoalsController < ApplicationController
  before_action :set_goal, only: %i[show edit update destroy]

  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.includes(:progresses).all
  end

  # GET /goals/1
  # GET /goals/1.json
  def show; end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit; end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(goal_params)

    respond_to do |format|
      if @goal.save
        format.html { redirect_to @goal, notice: 'Goal was successfully created.' }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_url, notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_goal
    @goal = Goal.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def goal_params
    params.require(:goal).permit(:name, :benchmark)
  end
end

app/helpers/goals_helper.rb
# frozen_string_literal: true

module GoalsHelper
  def display_progress(progress_entries_hash, date)
    amount = progress_entries_hash[date.to_date.to_s]
    amount.blank? ? "-" : amount
  end
end

app/views/goals/_form.html.slim
= form_for [@goal] do |f|
  = error_messages_for f.object

  .field
    = f.label :name, class: 'label'
    .control= f.text_field :name, placeholder: f.object.class.human_attribute_name(:name), class: 'input'
  .field
    = f.label :benchmark, class: 'label'
    .control= f.number_field :benchmark, placeholder: f.object.class.human_attribute_name(:benchmark), class: 'input', step: :any

  .field.is-grouped
    p.control
      = submit_tag t('.save'), class: 'button is-primary', data: {disable_with: "Saving..."}
      = link_to "Cancel", [:goals], class: 'button is-text'


    p.control.has-text-right
      - if f.object.persisted? # and policy(f.object).destroy?
        = link_to [f.object], method: :delete, class: 'button is-danger is-inverted', data: {confirm: t('.destroy.title')} do
          i.fa.fa-trash
          = t('.destroy.button')

app/views/goals/edit.html.slim
h1 Editing goal

== render 'form'

=> link_to 'Show', @goal
'|
=< link_to 'Back', goals_path

app/views/goals/index.html.slim
h1.title Listing goals

table.table
  thead
    tr
      th Name
      - ProgressQuery.weekdays.each do |day|
        th = day
      th
      th
      th

  tbody
    - @goals.each do |goal|
      tr
        td = goal.name
        - ProgressQuery.new(goal).week_entries.each do |entry|
          td
            - if entry.nil?
              '-
            - elsif entry.to_f >= goal.benchmark
              span.tag.is-success = entry
            - else
              span.tag.is-danger = entry
        td = link_to 'Show', goal
        td = link_to 'Edit', edit_goal_path(goal)
        td = link_to 'Destroy', goal, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Goal', new_goal_path
'|
= link_to 'New Progress', new_progress_path

app/views/goals/new.html.slim
h1 New goal

== render 'form'

= link_to 'Back', goals_path

app/views/goals/show.html.slim
p#notice = notice

p
  strong Name:
  = @goal.name
p
  strong Benchmark:
  = @goal.benchmark

=> link_to 'Edit', edit_goal_path(@goal)
'|
=< link_to 'Back', goals_path