config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :progresses
  resources :goals
  root to: 'goals#index'
end

app/controllers/goal_progresses_controller.rb
# frozen_string_literal: true

# GoalProgressesController
class GoalProgressesController < ApplicationController
  before_action :set_goal_progress, only: %i[show edit update destroy]

  # GET /goal_progresses
  # GET /goal_progresses.json
  def index
    @goal_progresses = GoalProgress.all
  end

  # GET /goal_progresses/1
  # GET /goal_progresses/1.json
  def show; end

  # GET /goal_progresses/new
  def new
    @goal_progress = GoalProgress.new
  end

  # GET /goal_progresses/1/edit
  def edit; end

  # POST /goal_progresses
  # POST /goal_progresses.json
  def create
    @goal_progress = GoalProgress.new(goal_progress_params)

    respond_to do |format|
      if @goal_progress.save
        format.html { redirect_to @goal_progress, notice: 'Progress was successfully created.' }
        format.json { render :show, status: :created, location: @goal_progress }
      else
        format.html { render :new }
        format.json { render json: @goal_progress.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goal_progresses/1
  # PATCH/PUT /goal_progresses/1.json
  def update
    respond_to do |format|
      if @goal_progress.update(goal_progress_params)
        format.html { redirect_to @goal_progress, notice: 'Progress was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal_progress }
      else
        format.html { render :edit }
        format.json { render json: @goal_progress.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goal_progresses/1
  # DELETE /goal_progresses/1.json
  def destroy
    @goal_progress.destroy
    respond_to do |format|
      format.html { redirect_to goal_progresses_url, notice: 'Progress was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_goal_progress
    @goal_progress = GoalProgress.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def goal_progress_params
    params.require(:goal_progress).permit(:goal_id, :achieve, :achieve_at)
  end
end

app/views/goal_progresses/_form.html.slim
= form_for [@goal_progress] do |f|
  = error_messages_for f.object

  .field
    = f.label :goal, class: 'label'
    .control= f.collection_select(:goal_id, Goal.all, :id, :name)

  .field
    = f.label :achieve_at, class: 'label'
    .control= f.date_field :achieve_at, placeholder: f.object.class.human_attribute_name(:achieve_at), class: 'input', required: true

  .field
    = f.label :achieve, class: 'label'
    .control= f.number_field :achieve, placeholder: f.object.class.human_attribute_name(:achieve), class: 'input', required: true

  .field.is-grouped
    p.control
      = submit_tag t('.save'), class: 'button is-primary', data: {disable_with: "Saving..."}
      = link_to "Cancel", [:goal_progresses], class: 'button is-text'

    p.control.has-text-right
      - if f.object.persisted? # and policy(f.object).destroy?
        = link_to [f.object], method: :delete, class: 'button is-danger is-inverted', data: {confirm: t('.destroy.title')} do
          i.fa.fa-trash
          = t('.destroy.button')

app/views/goal_progresses/edit.html.slim
h1 Editing progress

== render 'form'

=> link_to 'Show', @goal_progress
'|
=< link_to 'Back', goal_progresses_path

app/views/goal_progresses/index.html.slim
h1.title Listing progresses

table.table
  thead
    tr
      th Goal
      th Achieve At
      th Achieve
      th
      th
      th

  tbody
    - @goal_progresses.each do |progress|
      tr
        td = progress.goal.name
        td = progress.achieve_at
        td = progress.achieve
        td = link_to 'Show', progress
        td = link_to 'Edit', edit_goal_progress_path(progress)
        td = link_to 'Destroy', progress, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Progress', new_goal_progress_path

app/views/goal_progresses/new.html.slim
h1 New progress

== render 'form'

= link_to 'Back', goal_progresses_path

app/views/goal_progresses/show.html.slim
p#notice = notice

p
  strong Goal:
  = @goal_progress.goal.name
p
  strong achieve_at:
  = @goal_progress.achieve_at

p
  strong achieve_at:
  = @goal_progress.achieve

=> link_to 'Edit', edit_goal_progress_path(@goal_progress)
'|
=< link_to 'Back', goal_progresses_path